### ISSUE TITLE
Duplicates around `\r\n` are not detected

### ISSUE THREAD

**Issue by a2937** [wooorm/retext-repeated-words#10]
### Initial checklist

- [X] I read the [support docs](https://github.com/retextjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/retextjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/retextjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aretextjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

retext-repeated-words@4.2.0

### Steps to reproduce

Background: I was testing to see how well this plugin worked in the spellchecker-cli package when I ran into an unexpected assertion error. The expression `Well, it it doesn’t have to to be. Like a fish in the\r\nthe sea.` didn't catch the repeated `the`. Being highly interested in what was causing it; I eventually traced it back to this package and reproduced my example in the local test folder.

I made my local test.js look like the following: https://pastebin.com/ibNziPtb

It had failed. Here is a screenshot. 

![Unexpected Problem](https://i.imgur.com/APmKatg.png)

It hadn't even been caught as an error. I expect it didn't read the \r\n as a whitespace character and maybe need to be take it up with people behind the `nlcst` package if my suspicions are correct. 

### Expected behavior

There should have been three strings in the messages array in the example like there is with the \n example. 

### Affected runtime and version

node@16.14.0

### Affected package manager and version

npm@8.5.0

### Affected OS and version

Windows 10 

### Build and bundle tools

Other (please specify in steps to reproduce)

**Comment by wooorm** [comment]
Thanks, found it!
