### ISSUE TITLE
Better Documentation

### ISSUE THREAD

**Issue by Zamiell** [wooorm/retext-repeated-words#7]
Hello,

Thanks for the linter. I successfully got "retext-repeated-words" working with my entire repository, but it took me wayyy longer than it should have due to lacking documentation.

Can you add this example to the main README.md file? I would guess that the main use case for this linter would be to lint more than one file at a time, so this example would help a lot.

```
// A script to use retext-repeated-words to lint an entire directory / repository

const path = require('path');
const vfileGlob = require('vfile-glob');
const unified = require('unified');
const english = require('retext-english');
const repeated = require('retext-repeated-words');
const stringify = require('retext-stringify');
const report = require('vfile-reporter');

const rootDir = path.join(__dirname, '..'); // The root directory of the project
vfileGlob(`${rootDir}/**`, { // Match every file matching this glob
  ignore: [ // Add specific ignore globs here relating to your particular directory structure
    `${rootDir}/.git/**`,
    `${rootDir}/img/**`,
    `${rootDir}/misc/*.pdf`,
    `${rootDir}/linters/node_modules/**`,
    `${rootDir}/linters/package-lock.json`,
    `${rootDir}/LICENSE`,
  ],
}).subscribe({
  next(file) {
    unified()
    .use(english)
    .use(repeated)
    .use(stringify)
    .process(file, function(err, file) {
      const output = report(err || file, {
        quiet: true, // Only output on a warning or an error
      }).trim();
      if (output) {
        console.error(output);
      }
    })
  },
});
```

**Comment by ChristianMurphy** [comment]
@Zamiell Thanks for reaching out! and looking into how this can be run across multiple files!

In it's current from this doesn't appear to be an issue or a feature request.
If it's a question, on how to best approach this https://spectrum.chat/unified/retext would be the place to ask (there likely a more generic and potentially simpler approach using https://github.com/unifiedjs/unified-args)
If this is a code suggestion please open a PR.

Thanks!

**Comment by Zamiell** [comment]
ok, i opened a pull request, https://github.com/retextjs/retext-repeated-words/pull/8
